CREATE DATABASE Car_rental_company;

CREATE TABLE CARS (
ID INT PRIMARY KEY IDENTITY(1,2),
NAME NVARCHAR(200) NOT NULL,
COLOR VARCHAR(100) ,
MODEL NVARCHAR(100));

SELECT * FROM CARS;

CREATE TABLE CUSTOMER (
ID INT PRIMARY KEY IDENTITY(1,2),
NAME NVARCHAR(400) NOT NULL,
AGE INT CHECK (AGE>=18),
PHONE INT NOT NULL);

SELECT * FROM CUSTOMER;

CREATE TABLE RESERVATION(
ID INT PRIMARY KEY IDENTITY(1,2),
START_TIME DATETIME NOT NULL,
END_TIME DATETIME NOT NULL) ;
SELECT * FROM RESERVATION;

CREATE TABLE PAYMENT(
ID INT PRIMARY KEY IDENTITY(1,2),
BATCH BIT NOT NULL );

SELCET * FROM PAYMENT;

CREATE TABLE CUST_RESER(
ID_RESER INT ,
FOREIGN KEY (ID_RESER) REFERENCES RESERVATION(ID)
ID_COUST INT,
FOREIGN KEY (ID_COUST) REFERENCES CUSTOMER(ID));

SELECT * FROM CUST_RESER;

CREATE TABLE CAR_CUST(
ID_CUST INT,
FOREIGN KEY (ID_CUST) REFERENCES CUSTOMER(ID),
ID_CARS INT,
FOREIGN KEY (ID_CARS) REFERENCES CARS(ID));

SELECT * FROM CAR_CUST;

CREATE TABLE CAR_RESER(
ID_CARS INT,
FOREIGN KEY (ID_CARS) REFERENCES CARS(ID),
ID_RESER INT,
FOREIGN KEY (ID_RESER) REFERENCES RESERVATION(ID));

SELECT * FROM CAR_RESER;


SELECT * FROM RESERVATION
LEFT JOIN  CUSTOMER ON ID,NAME 
RIGHT JOIN SELECT * FROM RESERVATION ;
 
